# This pubspec is currently mainly used to make it easier to develop on dart2js
# by making it a standalone package.
name: compiler
#version: do-not-upload
dependencies:
  package_config: ^0.1.1
  js_ast:
    path: ../js_ast
  js_runtime:
    path: ../../sdk/lib/_internal/js_runtime
  sdk_library_metadata:
    path: ../../sdk/lib/_internal/sdk_library_metadata

# Uncomment if running gclient, so you can depend directly on the downloaded
# versions of dart2js's transitive dependencies:
#
# dependency_overrides:
#   package_config:
#     path: ../../third_party/pkg/package_config
#   path:
#     path: ../../third_party/pkg/path
#   charcode:
#     path: ../../third_party/pkg/charcode
